name: Clock_in

on:
  schedule:
    - cron: '0 23,2 * * *'

  workflow_dispatch:

jobs:
  Clock_in:
    runs-on: ubuntu-latest

    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install packages 
        run: pip3 install -r requirements.txt

      - name: Run the script
        env:
          XUHAO: ${{ secrets.XUHAO }}
          MIMA: ${{ secrets.MIMA }}
          PUSHPLUS: ${{ secrets.PUSHPLUS }}
        run: python clockIn_gzhu.py
